#ifndef FRESNEL_ZONE_H
#define FRESNEL_ZONE_H

#include "../geometry/line.h"
#include "../geometry/polygon.h"

#include <vector>
#include <string>

/*
Calculate the 2D Fresnel zone using a start point, an end point
and the radius of the ellipsoid at the center between the two points
and return the discretized ellipse as a Polygon object.

Args:
 - start_point : Start point of the direct line
 - end_point   : End point of the direct line
 - radius      : Radius of the ellipsoid at the center of the direct line
 - n_samples   : Number of samples to determine on the ellipse of the
                 Fresnel zone

Returns:
 - Sampled points on the ellipse as a Polygon object
*/
Polygon fresnelZone (
    Vector& start_point, Vector& end_point,
    double radius,
    uint n_samples
);

/*
Find all the tiles that are either partially or completely inside the
ground area polygon.

Args:
 - ground_area : Ground area ellipse as a Polygon object
                 (generated by signalConeGroundArea)

Returns:
 - List of tile names
*/
std::vector<std::string> tilesInGroundArea ( Polygon& ground_area );

/*
Find all polygons in the vector tiles that are located within the
ground area

Args:
 - polygons :    Reference to the list of polygons where the polygons
                 inside the ground area should be stored in
 - ground_area : Ground area as a Polygon object

Returns:
 - Status code:
    - SUCCESS

    - TILE_NOT_AVAILABLE
*/
int getPolygonsInGroundArea (
    std::vector<Polygon>& polygons,
    Polygon& ground_area
);

#endif
