#ifndef FRESNEL_ZONE_H
#define FRESNEL_ZONE_H

#include "../geometry/line.h"
#include "../geometry/polygon.h"

#include <vector>
#include <string>

/*
Calculate the 2D Fresnel zone using a start point, an end point
and the radius of the ellipsoid at the center between the two points
and return the discretized ellipse as a Polygon object.

Args:
 - start_point : Start point of the direct line
 - end_point   : End point of the direct line
 - nth_zone    : Zone number of the Fresnel zone
 - freq        : Frequency of the signal in Hz
 - n_samples   : Number of samples to determine on the ellipse of the
                 Fresnel zone

Returns:
 - Sampled points on the ellipse as a Polygon object
*/
Polygon fresnelZone (
    Vector& start_point, Vector& end_point,
    int nth_zone,
    double freq,
    uint n_samples
);

/*
Find all the tiles that are either partially or completely inside the
ground area polygon.

Args:
 - ground_area : Ground area ellipse as a Polygon object
                 (generated by signalConeGroundArea)

Returns:
 - List of tile names
*/
std::vector<std::string> tilesInGroundArea ( Polygon& ground_area );


#endif
