#ifndef STATUS_CODES_H
#define STATUS_CODES_H

enum Statuscodes {
    // Line
    LINES_INTERSECT,
    LINES_NO_INTERSECT,
    LINES_IDENTICAL,
    LINES_PARALLEL,
    POINTS_IDENTICAL,

    // Line / Plane
    VECTOR_LENGTH_0,
    ALL_COORDINATES_ZERO,
    VECTORS_LINEAR_DEPENDANT,
    LINE_INTERSECTS_PLANE,
    LINE_PARALLEL_TO_PLANE,
    LINE_ON_PLANE,
    CREATION_SUCCEEDED,

    // Polygon
    POINT_DUPLICATE,
    POINT_ADDED,
    POINT_NOT_ON_BASE_PLANE,
    POLYGON_NOT_INITIALIZED,
    TOO_FEW_POLYGON_POINTS,

    // Downloader
    INVALID_URL,
    DOWNLOAD_SUCCESSFUL,
    FILE_NOT_FOUND,
    FILE_NOT_CREATABLE,
    FILE_ALREADY_EXISTS,
    FILE_CREATED,

    // Tiles
    TILE_SIZES_UNEQUAL,
    TILES_MASKED,
    BINARY_FILE_NOT_FOUND,
    CORRUPT_BINARY_FILE,
    READ_BINARY_FILE_SUCCESS,
    BINARY_FILE_NOT_CREATABLE,
    BINARY_FILE_CREATED
};

#endif
